# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aleshin8sergey/Workspace/Coursework/My_Alg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aleshin8sergey/Workspace/Coursework/My_Alg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aleshin8sergey/Workspace/Coursework/My_Alg/CMakeFiles /home/aleshin8sergey/Workspace/Coursework/My_Alg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aleshin8sergey/Workspace/Coursework/My_Alg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named My_VJ_alg

# Build rule for target.
My_VJ_alg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 My_VJ_alg
.PHONY : My_VJ_alg

# fast build rule for target.
My_VJ_alg/fast:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/build
.PHONY : My_VJ_alg/fast

IntImg.o: IntImg.cpp.o

.PHONY : IntImg.o

# target to build an object file
IntImg.cpp.o:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/IntImg.cpp.o
.PHONY : IntImg.cpp.o

IntImg.i: IntImg.cpp.i

.PHONY : IntImg.i

# target to preprocess a source file
IntImg.cpp.i:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/IntImg.cpp.i
.PHONY : IntImg.cpp.i

IntImg.s: IntImg.cpp.s

.PHONY : IntImg.s

# target to generate assembly for a file
IntImg.cpp.s:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/IntImg.cpp.s
.PHONY : IntImg.cpp.s

SameScale.o: SameScale.cpp.o

.PHONY : SameScale.o

# target to build an object file
SameScale.cpp.o:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/SameScale.cpp.o
.PHONY : SameScale.cpp.o

SameScale.i: SameScale.cpp.i

.PHONY : SameScale.i

# target to preprocess a source file
SameScale.cpp.i:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/SameScale.cpp.i
.PHONY : SameScale.cpp.i

SameScale.s: SameScale.cpp.s

.PHONY : SameScale.s

# target to generate assembly for a file
SameScale.cpp.s:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/SameScale.cpp.s
.PHONY : SameScale.cpp.s

haar.o: haar.cpp.o

.PHONY : haar.o

# target to build an object file
haar.cpp.o:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/haar.cpp.o
.PHONY : haar.cpp.o

haar.i: haar.cpp.i

.PHONY : haar.i

# target to preprocess a source file
haar.cpp.i:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/haar.cpp.i
.PHONY : haar.cpp.i

haar.s: haar.cpp.s

.PHONY : haar.s

# target to generate assembly for a file
haar.cpp.s:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/haar.cpp.s
.PHONY : haar.cpp.s

workProt.o: workProt.cpp.o

.PHONY : workProt.o

# target to build an object file
workProt.cpp.o:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/workProt.cpp.o
.PHONY : workProt.cpp.o

workProt.i: workProt.cpp.i

.PHONY : workProt.i

# target to preprocess a source file
workProt.cpp.i:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/workProt.cpp.i
.PHONY : workProt.cpp.i

workProt.s: workProt.cpp.s

.PHONY : workProt.s

# target to generate assembly for a file
workProt.cpp.s:
	$(MAKE) -f CMakeFiles/My_VJ_alg.dir/build.make CMakeFiles/My_VJ_alg.dir/workProt.cpp.s
.PHONY : workProt.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... My_VJ_alg"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... IntImg.o"
	@echo "... IntImg.i"
	@echo "... IntImg.s"
	@echo "... SameScale.o"
	@echo "... SameScale.i"
	@echo "... SameScale.s"
	@echo "... haar.o"
	@echo "... haar.i"
	@echo "... haar.s"
	@echo "... workProt.o"
	@echo "... workProt.i"
	@echo "... workProt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

